### ISSUE TITLE
gzip: train.txt.gz: not in gzip format

### ISSUE THREAD

**Issue by SeekPoint** [ketranm/RMN#1]
rzai@rzai00:~/prj/RMN/data/en$ gunzip  train.txt.gz 

gzip: train.txt.gz: not in gzip format
rzai@rzai00:~/prj/RMN/data/en$ 
rzai@rzai00:~/prj/RMN/data/en$

**Comment by SeekPoint** [comment]
rzai@rzai00:~/prj/RMN/data/en$ gzip -d train.txt.gz 

gzip: train.txt.gz: not in gzip format
rzai@rzai00:~/prj/RMN/data/en$

**Comment by ketranm** [comment]
the data was pushed using [git-lfs](https://git-lfs.github.com/). If you have git-lfs installed, you can just do `git lfs pull` to get the data.
